/* STUDIO producing MOVIEs with more than 2 ACTORS */

SELECT 
	DISTINCT M.STUDIONAME	/* ONLY one record per GROUP */
FROM 
	MOVIE M
INNER JOIN
	STARSIN S
ON
	(M.TITLE = S.MOVIETITLE and M.[YEAR] = S.MOVIEYEAR)
GROUP BY
	M.STUDIONAME,
	M.TITLE, /* PK */
	M.YEAR	 /* PK */
HAVING
	COUNT(S.STARNAME) >= 2